export const articleCard: string;
export const date: string;
export const dateWrapper: string;
export const linkText: string;
export const readMore: string;
export const separator: string;
export const tagLink: string;
export const thumbnailImage: string;
export const thumbnailWrapper: string;
